# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ActiveRecord::Base.transaction do

User.destroy_all
Question.destroy_all
  100.times do 
    name = Faker::Name.unique.name
    email = Faker::Internet.unique.email
    password = Faker::Internet.password(min_length: 6)
    User.create!({username:name, email:email, password: password})
  end 

  # Jen = User.create!({username:"Jen", email:"jen@gamil.com", password: 123456789})
  # Pan = User.create!({username:"Pan", email:"pan@gamil.com", password: 1234567890})
  Lily = User.create!({username:"Lily", email:"lily@gamil.com", password: 1234567})
  # Tom = User.create!({username:"Tom", email:"tom@gmail.com", password: 12345678900})

  ids = User.ids


  question1 = Question.create({user_id: ids.sample, title: "What do these three dots in React do?", body: "What does the ... do in this React (using JSX) code and what is it called?"})
  question2 = Question.create({user_id: ids.sample, title: "Cannot Call Mixin Function from Initialize - Ruby", body: "I have a class called Amazon. When I instantiate that class I try to call a block function that I have in an helper function that I extended in my class. When I call this function from within the initialize function, I get the error: undefined method 'api_caller' for Class:Class. When I call the function outside of the initialize function everything works as expected. I assume this has something to do with the way objects are built in Ruby but I don't know how to get around the error."})
  question3 = Question.create({user_id: ids.sample, title: "Changing a MongoDB query into a Postgres query in Javascript", body: "I'm having a challenge converting this query. I have had success with others but this one combines multiple fields and I need some help. This is to get the dates to create a reservation."})
  question4 = Question.create({user_id: ids.sample, title: "How to dispatch a Redux action with a timeout?", body: "I have an action that updates notification state of my application. Usually, this notification will be an error or info of some sort. I need to then dispatch another action after 5 seconds that will return the notification state to initial one, so no notification. The main reason behind this is to provide functionality where notifications disappear automatically after 5 seconds. I had no luck with using setTimeout and returning another action and can't find how this is done online. So any advice is welcome."})
  question5 = Question.create({user_id:ids.sample, title: "Pros/cons of using redux-saga with ES6 generators vs redux-thunk with ES2017 async/await", body: "There is a lot of talk about the latest kid in redux town right now, redux-saga/redux-saga. It uses generator functions for listening to/dispatching actions. Before I wrap my head around it, I would like to know the pros/cons of using redux-saga instead of the approach below where I'm using redux-thunk with async/await."})
  question6 = Question.create({user_id:ids.sample, title: "What are differences between redux, react-redux, redux-thunk?", body: "I am using React + Flux. Our team is planning to move from flux to redux. Redux is very confusing for me coming from flux world. In flux control flow is simple from Components -> actions -> Store and store updates back components. Its simple and very clear. But in redux its confusing. There is no store here, yes there are some examples without using store. I went through several tutorials, it seems everyone has their own style of implementation. Some are using Containers and some are not. (I don't know this Containers concept and not able to understand what mapStateToProps, mapDispatchToProps does)."})
  question7 = Question.create({user_id:ids.sample, title: "Polymer-redux : How to store data in redux using polymer?", body: "I have created polymer app with redux. redux working fine, it stored data. but when I reload page it flush the data. how can I store data for next page? I want to store data in redux like local storage. Can anyone help me?"})
  question8 = Question.create({user_id:ids.sample, title: "Is react-redux required to use with redux-persist?", body:"I'm using React-native and Redux, but my app is very small and simple, so I thought that redux-react isn't necessary overhead, so I didn't use it. I just import store whenever I need because it is a singleton anyways. But now with redux-persist I'm getting an error from App.js, so I guess it might be because I don't use store Provider. Is it true?"})
  question9 = Question.create({user_id:ids.sample, title: "Redux Watch not responding to changes in redux store", body:"I am trying to monitor the change in a redux store attribute by subscribing to the change using redux watch. For one attribute it works fine. For another, I am making an API request in the reducer (can't make async requests in the actions). I have verified that the redux state does indeed get updated by creating a button to display the new information. However, my component isn't actually subscribing to the change. Does anyone know why this is?"})
  question10 = Question.create({user_id:ids.sample, title: "Do I have to use firebase-redux firestore-redux to connect redux to firebase", body:"I already managed to connect firebase and firestore with redux without using firebase-redux and firestore-redux packages. What differences does it make to using them?"})
  question11 = Question.create({user_id:ids.sample, title: "How to pass in a react component into another react component to transclude the first component's content?", body:"Is there a way to pass one component into another react component? I want to create a model react component and pass in another react component in order to transclude that content."})
  question12 = Question.create({user_id:ids.sample, title: "When to use ES6 class based React components vs. functional ES6 React components?", body:"After spending some time learning React I understand the difference between the two main paradigms of creating components. My question is when should I use which one and why? What are the benefits/tradeoffs of one over the other?"})
  question13 = Question.create({user_id:ids.sample, title: "Use Python 3 to monitor a folder and see if files are being uploaded", body:"I am not trying to do a website, I want to have this python script running as a third-party application. I am trying to have the script monitor every file in the whole computer or in a specific folder to see if any file is being uploaded/read. One example would be uploading a file (such as test.txt) onto Google Drive, and I hope that my script could detect that. I don't really need information about the file, just to monitor if any is being uploaded. Is there any way to do this?"})
  question14 = Question.create({user_id:ids.sample, title: "What command should I run in terminal to build a chrome application with react?", body:"I've tried to build this chrome extension found on github using 'npm install' and 'npm run build' but it doesn't create it correcly. What command should I run to compile/build it?"})
  question15 = Question.create({user_id:ids.sample, title: "How to set the value into 0 when there's no input and seperate data based on date in angular", body:"how to segregate the data and display the PRN children based on the date for example january then if there's a data which is machine 1 then have assetCode: PRN it will display on the children header and then it will display the value if there's another machine 2 then have assetCode: PRN1 it will added on january children. then if the machine 1 have no assetCode: PRN1 then it will set at 0, same as machine 2"})
  question16 = Question.create({user_id:ids.sample, title: "Process.Start() results in Access Denied exception despite Full Control for Everyone group", body:"My project output contains an executable called key_gen.exe that I'm trying to run. The executable is not built by the project, but copied in after the fact. With the code below I receive an Access Denied exception."})
  question17 = Question.create({user_id:ids.sample, title: "How can I convert bootstrap template with rails application?", body:"I downloaded bootstrap theme files, it includes the static HTML, CSS and js files. If I'm using the same bootstrap theme in rails app, how can I integrate those files with rails application"})
  question18 = Question.create({user_id:ids.sample, title: "Is it possible that Ruby Marshallng may work differently with different versions of ruby?", body:"I need to send complex object( EbayAPI object may have big amount of data) to sidekiq. So, marshaling looks like a good solution. What I am afraid of: Is it possible that Ruby Marshaling may work differently with different versions of ruby? So, one day I will update ruby version, and due load marshaled object the original object would be not the same, as before marshaled, is it possible?"})
  question19 = Question.create({user_id:ids.sample, title: "Auto generate PIN number for gravity form to unlock fields for members using paid membership pro", body:"Basically, I’m using paid membership pro, but I need to send a PIN number to after approving them, the PIN number to unlock last field before submitting forms ,after completion the dorm will go to different members as pdf. Any help Thanks in advance"})
  question20 = Question.create({user_id:ids.sample, title: "How can I allow a user to only access a view once every 30 minutes in Django?", body:"I am building an app that lets users update a webpage, but I want to restrict any user from being able to make updates every 20-30 minutes. Would I be able to simply add this logic to a view definition?"})
  question21 = Question.create({user_id:ids.sample, title: "How do I add .cpp included files to the dependencies in android.mk?", body:"In our Android project, we have several tens of C and CPP files which we #include through one container file for the build. The container file is listed in LOCAL_SRC_FILES, since that's what's compiled. However, when I edit one of the included .cpp files, that doesn't seem to trigger a build. If I were in total control of the make file, I'd just include all those files as dependencies for the relevant compile step. However, android.mk handles making all those compile dependencies in general, so I don't know where to insert them."})
  question22 = Question.create({user_id:ids.sample, title: "How does tail recursion really help over traditional recursion?", body:"I was reading up about the difference between tail recursion and Traditional recursion and find it mentioned that Tail Recursion however is a form of recursion that doesn’t use any stack space, and thus is a way to use recursion safely."})
  question23 = Question.create({user_id:ids.sample, title: "How do you configure multiple-platform C programming in Code?", body:"I am working on a C project. Some files are meant to be cross-platform, and some are for particular platforms in different directories. I'd like to use Visual Studio Code to at least write and read all the files. I already have header files for different platforms on my system and I'd like to find a way to configure this project so that macOS files use macOS headers with commonly defined macOS macros, and windows files use Windows headers with commonly defined Windows macros, and shared files using whatever platform I choose. Is this possible?"})
  question24 = Question.create({user_id:ids.sample, title: "I want to downgrade my application target sdk version 29 to 28 can google play console allowed this?", body:"I just submitted my application with target sdk version 29 but i am facing some crashes can i downgrade it to 28 and submit it again?"})
  question25 = Question.create({user_id:ids.sample, title: "Is there a simpler syntax for member decorators for methods in Python 3?", body:"I changed a class which had a function that had to be ran prior to running a number of other functions. The function is now a decorator. But the syntax, which I came up with, seems very unintuitive."})

  
  answer1_1 = Answer.create!({user_id:ids.sample, body:"As you know ... are called Spread Attributes which the name represents it allows an expression to be expanded.", question_id:1})
  answer1_2 = Answer.create!({user_id:ids.sample, body:"There's another use for the three dots which is known as Rest Parameters and it makes it possible to take all of the arguments to a function in as one array.", question_id:1})
  answer1_3 = Answer.create!({user_id:ids.sample, body:"That's property spread notation. It was added in ES2018 (spread for arrays/iterables was earlier, ES2015), but it's been supported in React projects for along time via transpilation (as JSX spread attributes even though you could do it elsewhere, too, not just attributes).", question_id:1})
  answer3_1 = Answer.create!({user_id:ids.sample, body:"I came up with this: var getByDate = function (restId, date, callback)", question_id:3})
  answer4_1 = Answer.create!({user_id:ids.sample, body:"Don’t fall into the trap of thinking a library should prescribe how to do everything. If you want to do something with a timeout in JavaScript, you need to use setTimeout. There is no reason why Redux actions should be any different. Redux does offer some alternative ways of dealing with asynchronous stuff, but you should only use those when you realize you are repeating too much code. Unless you have this problem, use what the language offers and go for the simplest solution.", question_id:4})
  answer4_2 = Answer.create!({user_id:ids.sample, body:"As Dan Abramov said, if you want more advanced control over your async code, you might take a look at redux-saga. This answer is a simple example, if you want better explanations on why redux-saga can be useful for your application, check this other answer.", question_id:4})
  answer5_1 = Answer.create!({user_id:ids.sample, body:"The first thing to notice is that we're calling the api functions using the form yield call(func, ...args). call doesn't execute the effect, it just creates a plain object like {type: 'CALL', func, args}. The execution is delegated to the redux-saga middleware which takes care of executing the function and resuming the generator with its result.", question_id:5})
  answer5_2 = Answer.create!({user_id:ids.sample, body:"I will add my experience using saga in production system in addition to the library author's rather thorough answer.", question_id:5})
  answer6_1 = Answer.create!({user_id:ids.sample, body:"Note that containers / smart components vs. dumb components is just a good way to structure your app.", question_id:6})
  answer6_2 = Answer.create!({user_id:ids.sample, body:"bellow image demonstrates how data flow in redux : how the data flows through Redux? Advantages of Redux are listed below:", question_id:6})
  answer7_1 = Answer.create!({user_id:ids.sample, body:"If you’re making a SPA (Single Page Application), then you don’t have to store the data. You can use PolymerElements app-route for routing inside a SPA.", question_id:7})
  answer9_1 = Answer.create!({user_id:ids.sample, body:"In order to make async requests with redux you should look into redux middleware, like redux-thunk, redux-observables or redux-saga", question_id:9})
  answer10_1 = Answer.create!({user_id:ids.sample, body:"Those packages are their own opinionated integrations of the two libraries. If you agree with their opinions then they'll save you setup time, if you've already set things up and don't need them then adding them is unecessary.", question_id:10})
  answer11_1 = Answer.create!({user_id:ids.sample, body:"You can use this.props.children to render whatever children the component contains:", question_id:11})
  answer11_2 = Answer.create!({user_id:ids.sample, body:"Note that children is a special prop in React, and the example above is syntactic sugar and is (almost) equivalent to <Wrapper children={<App/>}/>", question_id:11})
  answer12_1 = Answer.create!({user_id:ids.sample, body:"You have the right idea. Go with functional if your component doesn't do much more than take in some props and render. You can think of these as pure functions because they will always render and behave the same, given the same props. Also, they don't care about lifecycle methods or have their own internal state.", question_id:12})
  answer12_2 = Answer.create!({user_id:ids.sample, body:"Always try to use stateless functions (functional components) whenever possible. There are scenarios where you'll need to use a regular React class:", question_id:12})
  answer13_1 = Answer.create!({user_id:ids.sample, body:"You can have a try watchdog", question_id:13})
  answer17_1 = Answer.create!({user_id:ids.sample, body:"a layout, e.g. app/view/layouts/application.html.erb (or use your preferred templating framework, I prefer haml/slim) and edit it to keep header/footer elements only (aka the repeating elements for all pages, or a set of pages)", question_id:17})
  answer18_1 = Answer.create!({user_id:ids.sample, body:"Note, however, that the binary format used by Marshal.dump and Marshal.load is version dependent, and newer versions of Ruby are not guaranteed to be able to read marshalled objects written by older versions of Ruby.", question_id:18})
  answer18_2 = Answer.create!({user_id:ids.sample, body:"I'd recently a problem with Rails cache during migration from Rails 3.2 to Rails 4. App was unable to read AR models from the cache (same time simpler objects like hashes, array worked well). But ruby was the same.", question_id:18})
  answer20_1 = Answer.create!({user_id:ids.sample, body:"I would do something like this. I didnt test it but it should be close.Basically use request.session to keep track of last update.", question_id:20})
  answer20_2 = Answer.create!({user_id:ids.sample, body:"I figured out a pretty simple way to do this. I added a field to my model which will hold a value 10 minutes from the time the user posts an update. I can then just reference that field and check if the current time is greater(later) than 10 minutes after the users last update.", question_id:20})
  answer21_1 = Answer.create!({user_id:ids.sample, body:"And I include to in android.mk file like this", question_id:21})
  answer22_1 = Answer.create!({user_id:ids.sample, body:"The trick is that if the compiler notices the tail recursion, it can compile a goto instead. It will generate something like the following code:", question_id:22})
  answer22_2 = Answer.create!({user_id:ids.sample, body:"A function call is tail recursive when function call (recursive) is performed as final action. Since the current recursive instance is done executing at that point, no need to maintaining its stack frame.", question_id:22})
  answer23_1 = Answer.create!({user_id:ids.sample, body:"You'll need to use predefined preprocessor macros for the platform you are compiling for. For example, the predefined preprocessor macros (and examples) for Microsoft Visual Studio 2019 are defined here. Similarly, you will have to search for the predefined macros for each of the platform you are looking for.", question_id:23})
  answer24_1 = Answer.create!({user_id:ids.sample, body:"Yes, you can upload a new version that downgrades your targetSdkVersion - the Google Play target API level requirement only requires targeting API 28 or higher.", question_id:24})
  answer25_1 = Answer.create!({user_id:ids.sample, body:"Below is a runnable example that illustrates my suggestion of how it would be possible to move the decorator function completely out of the class:", question_id:25})

end